// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class TaskCategories extends Table
    with TableInfo<TaskCategories, TaskCategoriesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  TaskCategories(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> colorValue = GeneratedColumn<int>(
    'color_value',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> iconKey = GeneratedColumn<String>(
    'icon_key',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> sortOrder = GeneratedColumn<int>(
    'sort_order',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    name,
    colorValue,
    iconKey,
    sortOrder,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'task_categories';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  TaskCategoriesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return TaskCategoriesData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      name: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}name'],
      )!,
      colorValue: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}color_value'],
      )!,
      iconKey: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}icon_key'],
      )!,
      sortOrder: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}sort_order'],
      )!,
    );
  }

  @override
  TaskCategories createAlias(String alias) {
    return TaskCategories(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class TaskCategoriesData extends DataClass
    implements Insertable<TaskCategoriesData> {
  final String id;
  final String name;
  final int colorValue;
  final String iconKey;
  final int sortOrder;
  const TaskCategoriesData({
    required this.id,
    required this.name,
    required this.colorValue,
    required this.iconKey,
    required this.sortOrder,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['name'] = Variable<String>(name);
    map['color_value'] = Variable<int>(colorValue);
    map['icon_key'] = Variable<String>(iconKey);
    map['sort_order'] = Variable<int>(sortOrder);
    return map;
  }

  TaskCategoriesCompanion toCompanion(bool nullToAbsent) {
    return TaskCategoriesCompanion(
      id: Value(id),
      name: Value(name),
      colorValue: Value(colorValue),
      iconKey: Value(iconKey),
      sortOrder: Value(sortOrder),
    );
  }

  factory TaskCategoriesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return TaskCategoriesData(
      id: serializer.fromJson<String>(json['id']),
      name: serializer.fromJson<String>(json['name']),
      colorValue: serializer.fromJson<int>(json['colorValue']),
      iconKey: serializer.fromJson<String>(json['iconKey']),
      sortOrder: serializer.fromJson<int>(json['sortOrder']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'name': serializer.toJson<String>(name),
      'colorValue': serializer.toJson<int>(colorValue),
      'iconKey': serializer.toJson<String>(iconKey),
      'sortOrder': serializer.toJson<int>(sortOrder),
    };
  }

  TaskCategoriesData copyWith({
    String? id,
    String? name,
    int? colorValue,
    String? iconKey,
    int? sortOrder,
  }) => TaskCategoriesData(
    id: id ?? this.id,
    name: name ?? this.name,
    colorValue: colorValue ?? this.colorValue,
    iconKey: iconKey ?? this.iconKey,
    sortOrder: sortOrder ?? this.sortOrder,
  );
  TaskCategoriesData copyWithCompanion(TaskCategoriesCompanion data) {
    return TaskCategoriesData(
      id: data.id.present ? data.id.value : this.id,
      name: data.name.present ? data.name.value : this.name,
      colorValue: data.colorValue.present
          ? data.colorValue.value
          : this.colorValue,
      iconKey: data.iconKey.present ? data.iconKey.value : this.iconKey,
      sortOrder: data.sortOrder.present ? data.sortOrder.value : this.sortOrder,
    );
  }

  @override
  String toString() {
    return (StringBuffer('TaskCategoriesData(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('colorValue: $colorValue, ')
          ..write('iconKey: $iconKey, ')
          ..write('sortOrder: $sortOrder')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, name, colorValue, iconKey, sortOrder);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TaskCategoriesData &&
          other.id == this.id &&
          other.name == this.name &&
          other.colorValue == this.colorValue &&
          other.iconKey == this.iconKey &&
          other.sortOrder == this.sortOrder);
}

class TaskCategoriesCompanion extends UpdateCompanion<TaskCategoriesData> {
  final Value<String> id;
  final Value<String> name;
  final Value<int> colorValue;
  final Value<String> iconKey;
  final Value<int> sortOrder;
  final Value<int> rowid;
  const TaskCategoriesCompanion({
    this.id = const Value.absent(),
    this.name = const Value.absent(),
    this.colorValue = const Value.absent(),
    this.iconKey = const Value.absent(),
    this.sortOrder = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  TaskCategoriesCompanion.insert({
    required String id,
    required String name,
    required int colorValue,
    required String iconKey,
    this.sortOrder = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       name = Value(name),
       colorValue = Value(colorValue),
       iconKey = Value(iconKey);
  static Insertable<TaskCategoriesData> custom({
    Expression<String>? id,
    Expression<String>? name,
    Expression<int>? colorValue,
    Expression<String>? iconKey,
    Expression<int>? sortOrder,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (colorValue != null) 'color_value': colorValue,
      if (iconKey != null) 'icon_key': iconKey,
      if (sortOrder != null) 'sort_order': sortOrder,
      if (rowid != null) 'rowid': rowid,
    });
  }

  TaskCategoriesCompanion copyWith({
    Value<String>? id,
    Value<String>? name,
    Value<int>? colorValue,
    Value<String>? iconKey,
    Value<int>? sortOrder,
    Value<int>? rowid,
  }) {
    return TaskCategoriesCompanion(
      id: id ?? this.id,
      name: name ?? this.name,
      colorValue: colorValue ?? this.colorValue,
      iconKey: iconKey ?? this.iconKey,
      sortOrder: sortOrder ?? this.sortOrder,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (name.present) {
      map['name'] = Variable<String>(name.value);
    }
    if (colorValue.present) {
      map['color_value'] = Variable<int>(colorValue.value);
    }
    if (iconKey.present) {
      map['icon_key'] = Variable<String>(iconKey.value);
    }
    if (sortOrder.present) {
      map['sort_order'] = Variable<int>(sortOrder.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('TaskCategoriesCompanion(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('colorValue: $colorValue, ')
          ..write('iconKey: $iconKey, ')
          ..write('sortOrder: $sortOrder, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class TaskItems extends Table with TableInfo<TaskItems, TaskItemsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  TaskItems(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> title = GeneratedColumn<String>(
    'title',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> description = GeneratedColumn<String>(
    'description',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<int> startAt = GeneratedColumn<int>(
    'start_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> endAt = GeneratedColumn<int>(
    'end_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> scheduledDate = GeneratedColumn<int>(
    'scheduled_date',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> startTimeMinutes = GeneratedColumn<int>(
    'start_time_minutes',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> durationMinutes = GeneratedColumn<int>(
    'duration_minutes',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> categoryId = GeneratedColumn<String>(
    'category_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL REFERENCES task_categories(id)ON DELETE SET NULL',
  );
  late final GeneratedColumn<int> allDay = GeneratedColumn<int>(
    'all_day',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0 CHECK (all_day IN (0, 1))',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> priority = GeneratedColumn<int>(
    'priority',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1',
    defaultValue: const CustomExpression('1'),
  );
  late final GeneratedColumn<int> isCompleted = GeneratedColumn<int>(
    'is_completed',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_completed IN (0, 1))',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<String> recurrenceType = GeneratedColumn<String>(
    'recurrence_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'none\'',
    defaultValue: const CustomExpression('\'none\''),
  );
  late final GeneratedColumn<int> recurrenceWeekdays = GeneratedColumn<int>(
    'recurrence_weekdays',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT (CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER))',
    defaultValue: const CustomExpression(
      'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)',
    ),
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    title,
    description,
    startAt,
    endAt,
    scheduledDate,
    startTimeMinutes,
    durationMinutes,
    categoryId,
    allDay,
    priority,
    isCompleted,
    recurrenceType,
    recurrenceWeekdays,
    createdAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'task_items';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  TaskItemsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return TaskItemsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      title: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}title'],
      )!,
      description: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}description'],
      )!,
      startAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}start_at'],
      ),
      endAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}end_at'],
      ),
      scheduledDate: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}scheduled_date'],
      ),
      startTimeMinutes: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}start_time_minutes'],
      ),
      durationMinutes: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}duration_minutes'],
      ),
      categoryId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}category_id'],
      ),
      allDay: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}all_day'],
      )!,
      priority: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}priority'],
      )!,
      isCompleted: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}is_completed'],
      )!,
      recurrenceType: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}recurrence_type'],
      )!,
      recurrenceWeekdays: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}recurrence_weekdays'],
      )!,
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
    );
  }

  @override
  TaskItems createAlias(String alias) {
    return TaskItems(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class TaskItemsData extends DataClass implements Insertable<TaskItemsData> {
  final String id;
  final String title;
  final String description;
  final int? startAt;
  final int? endAt;
  final int? scheduledDate;
  final int? startTimeMinutes;
  final int? durationMinutes;
  final String? categoryId;
  final int allDay;
  final int priority;
  final int isCompleted;
  final String recurrenceType;
  final int recurrenceWeekdays;
  final int createdAt;
  const TaskItemsData({
    required this.id,
    required this.title,
    required this.description,
    this.startAt,
    this.endAt,
    this.scheduledDate,
    this.startTimeMinutes,
    this.durationMinutes,
    this.categoryId,
    required this.allDay,
    required this.priority,
    required this.isCompleted,
    required this.recurrenceType,
    required this.recurrenceWeekdays,
    required this.createdAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['title'] = Variable<String>(title);
    map['description'] = Variable<String>(description);
    if (!nullToAbsent || startAt != null) {
      map['start_at'] = Variable<int>(startAt);
    }
    if (!nullToAbsent || endAt != null) {
      map['end_at'] = Variable<int>(endAt);
    }
    if (!nullToAbsent || scheduledDate != null) {
      map['scheduled_date'] = Variable<int>(scheduledDate);
    }
    if (!nullToAbsent || startTimeMinutes != null) {
      map['start_time_minutes'] = Variable<int>(startTimeMinutes);
    }
    if (!nullToAbsent || durationMinutes != null) {
      map['duration_minutes'] = Variable<int>(durationMinutes);
    }
    if (!nullToAbsent || categoryId != null) {
      map['category_id'] = Variable<String>(categoryId);
    }
    map['all_day'] = Variable<int>(allDay);
    map['priority'] = Variable<int>(priority);
    map['is_completed'] = Variable<int>(isCompleted);
    map['recurrence_type'] = Variable<String>(recurrenceType);
    map['recurrence_weekdays'] = Variable<int>(recurrenceWeekdays);
    map['created_at'] = Variable<int>(createdAt);
    return map;
  }

  TaskItemsCompanion toCompanion(bool nullToAbsent) {
    return TaskItemsCompanion(
      id: Value(id),
      title: Value(title),
      description: Value(description),
      startAt: startAt == null && nullToAbsent
          ? const Value.absent()
          : Value(startAt),
      endAt: endAt == null && nullToAbsent
          ? const Value.absent()
          : Value(endAt),
      scheduledDate: scheduledDate == null && nullToAbsent
          ? const Value.absent()
          : Value(scheduledDate),
      startTimeMinutes: startTimeMinutes == null && nullToAbsent
          ? const Value.absent()
          : Value(startTimeMinutes),
      durationMinutes: durationMinutes == null && nullToAbsent
          ? const Value.absent()
          : Value(durationMinutes),
      categoryId: categoryId == null && nullToAbsent
          ? const Value.absent()
          : Value(categoryId),
      allDay: Value(allDay),
      priority: Value(priority),
      isCompleted: Value(isCompleted),
      recurrenceType: Value(recurrenceType),
      recurrenceWeekdays: Value(recurrenceWeekdays),
      createdAt: Value(createdAt),
    );
  }

  factory TaskItemsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return TaskItemsData(
      id: serializer.fromJson<String>(json['id']),
      title: serializer.fromJson<String>(json['title']),
      description: serializer.fromJson<String>(json['description']),
      startAt: serializer.fromJson<int?>(json['startAt']),
      endAt: serializer.fromJson<int?>(json['endAt']),
      scheduledDate: serializer.fromJson<int?>(json['scheduledDate']),
      startTimeMinutes: serializer.fromJson<int?>(json['startTimeMinutes']),
      durationMinutes: serializer.fromJson<int?>(json['durationMinutes']),
      categoryId: serializer.fromJson<String?>(json['categoryId']),
      allDay: serializer.fromJson<int>(json['allDay']),
      priority: serializer.fromJson<int>(json['priority']),
      isCompleted: serializer.fromJson<int>(json['isCompleted']),
      recurrenceType: serializer.fromJson<String>(json['recurrenceType']),
      recurrenceWeekdays: serializer.fromJson<int>(json['recurrenceWeekdays']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'title': serializer.toJson<String>(title),
      'description': serializer.toJson<String>(description),
      'startAt': serializer.toJson<int?>(startAt),
      'endAt': serializer.toJson<int?>(endAt),
      'scheduledDate': serializer.toJson<int?>(scheduledDate),
      'startTimeMinutes': serializer.toJson<int?>(startTimeMinutes),
      'durationMinutes': serializer.toJson<int?>(durationMinutes),
      'categoryId': serializer.toJson<String?>(categoryId),
      'allDay': serializer.toJson<int>(allDay),
      'priority': serializer.toJson<int>(priority),
      'isCompleted': serializer.toJson<int>(isCompleted),
      'recurrenceType': serializer.toJson<String>(recurrenceType),
      'recurrenceWeekdays': serializer.toJson<int>(recurrenceWeekdays),
      'createdAt': serializer.toJson<int>(createdAt),
    };
  }

  TaskItemsData copyWith({
    String? id,
    String? title,
    String? description,
    Value<int?> startAt = const Value.absent(),
    Value<int?> endAt = const Value.absent(),
    Value<int?> scheduledDate = const Value.absent(),
    Value<int?> startTimeMinutes = const Value.absent(),
    Value<int?> durationMinutes = const Value.absent(),
    Value<String?> categoryId = const Value.absent(),
    int? allDay,
    int? priority,
    int? isCompleted,
    String? recurrenceType,
    int? recurrenceWeekdays,
    int? createdAt,
  }) => TaskItemsData(
    id: id ?? this.id,
    title: title ?? this.title,
    description: description ?? this.description,
    startAt: startAt.present ? startAt.value : this.startAt,
    endAt: endAt.present ? endAt.value : this.endAt,
    scheduledDate: scheduledDate.present
        ? scheduledDate.value
        : this.scheduledDate,
    startTimeMinutes: startTimeMinutes.present
        ? startTimeMinutes.value
        : this.startTimeMinutes,
    durationMinutes: durationMinutes.present
        ? durationMinutes.value
        : this.durationMinutes,
    categoryId: categoryId.present ? categoryId.value : this.categoryId,
    allDay: allDay ?? this.allDay,
    priority: priority ?? this.priority,
    isCompleted: isCompleted ?? this.isCompleted,
    recurrenceType: recurrenceType ?? this.recurrenceType,
    recurrenceWeekdays: recurrenceWeekdays ?? this.recurrenceWeekdays,
    createdAt: createdAt ?? this.createdAt,
  );
  TaskItemsData copyWithCompanion(TaskItemsCompanion data) {
    return TaskItemsData(
      id: data.id.present ? data.id.value : this.id,
      title: data.title.present ? data.title.value : this.title,
      description: data.description.present
          ? data.description.value
          : this.description,
      startAt: data.startAt.present ? data.startAt.value : this.startAt,
      endAt: data.endAt.present ? data.endAt.value : this.endAt,
      scheduledDate: data.scheduledDate.present
          ? data.scheduledDate.value
          : this.scheduledDate,
      startTimeMinutes: data.startTimeMinutes.present
          ? data.startTimeMinutes.value
          : this.startTimeMinutes,
      durationMinutes: data.durationMinutes.present
          ? data.durationMinutes.value
          : this.durationMinutes,
      categoryId: data.categoryId.present
          ? data.categoryId.value
          : this.categoryId,
      allDay: data.allDay.present ? data.allDay.value : this.allDay,
      priority: data.priority.present ? data.priority.value : this.priority,
      isCompleted: data.isCompleted.present
          ? data.isCompleted.value
          : this.isCompleted,
      recurrenceType: data.recurrenceType.present
          ? data.recurrenceType.value
          : this.recurrenceType,
      recurrenceWeekdays: data.recurrenceWeekdays.present
          ? data.recurrenceWeekdays.value
          : this.recurrenceWeekdays,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('TaskItemsData(')
          ..write('id: $id, ')
          ..write('title: $title, ')
          ..write('description: $description, ')
          ..write('startAt: $startAt, ')
          ..write('endAt: $endAt, ')
          ..write('scheduledDate: $scheduledDate, ')
          ..write('startTimeMinutes: $startTimeMinutes, ')
          ..write('durationMinutes: $durationMinutes, ')
          ..write('categoryId: $categoryId, ')
          ..write('allDay: $allDay, ')
          ..write('priority: $priority, ')
          ..write('isCompleted: $isCompleted, ')
          ..write('recurrenceType: $recurrenceType, ')
          ..write('recurrenceWeekdays: $recurrenceWeekdays, ')
          ..write('createdAt: $createdAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    title,
    description,
    startAt,
    endAt,
    scheduledDate,
    startTimeMinutes,
    durationMinutes,
    categoryId,
    allDay,
    priority,
    isCompleted,
    recurrenceType,
    recurrenceWeekdays,
    createdAt,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TaskItemsData &&
          other.id == this.id &&
          other.title == this.title &&
          other.description == this.description &&
          other.startAt == this.startAt &&
          other.endAt == this.endAt &&
          other.scheduledDate == this.scheduledDate &&
          other.startTimeMinutes == this.startTimeMinutes &&
          other.durationMinutes == this.durationMinutes &&
          other.categoryId == this.categoryId &&
          other.allDay == this.allDay &&
          other.priority == this.priority &&
          other.isCompleted == this.isCompleted &&
          other.recurrenceType == this.recurrenceType &&
          other.recurrenceWeekdays == this.recurrenceWeekdays &&
          other.createdAt == this.createdAt);
}

class TaskItemsCompanion extends UpdateCompanion<TaskItemsData> {
  final Value<String> id;
  final Value<String> title;
  final Value<String> description;
  final Value<int?> startAt;
  final Value<int?> endAt;
  final Value<int?> scheduledDate;
  final Value<int?> startTimeMinutes;
  final Value<int?> durationMinutes;
  final Value<String?> categoryId;
  final Value<int> allDay;
  final Value<int> priority;
  final Value<int> isCompleted;
  final Value<String> recurrenceType;
  final Value<int> recurrenceWeekdays;
  final Value<int> createdAt;
  final Value<int> rowid;
  const TaskItemsCompanion({
    this.id = const Value.absent(),
    this.title = const Value.absent(),
    this.description = const Value.absent(),
    this.startAt = const Value.absent(),
    this.endAt = const Value.absent(),
    this.scheduledDate = const Value.absent(),
    this.startTimeMinutes = const Value.absent(),
    this.durationMinutes = const Value.absent(),
    this.categoryId = const Value.absent(),
    this.allDay = const Value.absent(),
    this.priority = const Value.absent(),
    this.isCompleted = const Value.absent(),
    this.recurrenceType = const Value.absent(),
    this.recurrenceWeekdays = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  TaskItemsCompanion.insert({
    required String id,
    required String title,
    this.description = const Value.absent(),
    this.startAt = const Value.absent(),
    this.endAt = const Value.absent(),
    this.scheduledDate = const Value.absent(),
    this.startTimeMinutes = const Value.absent(),
    this.durationMinutes = const Value.absent(),
    this.categoryId = const Value.absent(),
    this.allDay = const Value.absent(),
    this.priority = const Value.absent(),
    this.isCompleted = const Value.absent(),
    this.recurrenceType = const Value.absent(),
    this.recurrenceWeekdays = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       title = Value(title);
  static Insertable<TaskItemsData> custom({
    Expression<String>? id,
    Expression<String>? title,
    Expression<String>? description,
    Expression<int>? startAt,
    Expression<int>? endAt,
    Expression<int>? scheduledDate,
    Expression<int>? startTimeMinutes,
    Expression<int>? durationMinutes,
    Expression<String>? categoryId,
    Expression<int>? allDay,
    Expression<int>? priority,
    Expression<int>? isCompleted,
    Expression<String>? recurrenceType,
    Expression<int>? recurrenceWeekdays,
    Expression<int>? createdAt,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (title != null) 'title': title,
      if (description != null) 'description': description,
      if (startAt != null) 'start_at': startAt,
      if (endAt != null) 'end_at': endAt,
      if (scheduledDate != null) 'scheduled_date': scheduledDate,
      if (startTimeMinutes != null) 'start_time_minutes': startTimeMinutes,
      if (durationMinutes != null) 'duration_minutes': durationMinutes,
      if (categoryId != null) 'category_id': categoryId,
      if (allDay != null) 'all_day': allDay,
      if (priority != null) 'priority': priority,
      if (isCompleted != null) 'is_completed': isCompleted,
      if (recurrenceType != null) 'recurrence_type': recurrenceType,
      if (recurrenceWeekdays != null) 'recurrence_weekdays': recurrenceWeekdays,
      if (createdAt != null) 'created_at': createdAt,
      if (rowid != null) 'rowid': rowid,
    });
  }

  TaskItemsCompanion copyWith({
    Value<String>? id,
    Value<String>? title,
    Value<String>? description,
    Value<int?>? startAt,
    Value<int?>? endAt,
    Value<int?>? scheduledDate,
    Value<int?>? startTimeMinutes,
    Value<int?>? durationMinutes,
    Value<String?>? categoryId,
    Value<int>? allDay,
    Value<int>? priority,
    Value<int>? isCompleted,
    Value<String>? recurrenceType,
    Value<int>? recurrenceWeekdays,
    Value<int>? createdAt,
    Value<int>? rowid,
  }) {
    return TaskItemsCompanion(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      startAt: startAt ?? this.startAt,
      endAt: endAt ?? this.endAt,
      scheduledDate: scheduledDate ?? this.scheduledDate,
      startTimeMinutes: startTimeMinutes ?? this.startTimeMinutes,
      durationMinutes: durationMinutes ?? this.durationMinutes,
      categoryId: categoryId ?? this.categoryId,
      allDay: allDay ?? this.allDay,
      priority: priority ?? this.priority,
      isCompleted: isCompleted ?? this.isCompleted,
      recurrenceType: recurrenceType ?? this.recurrenceType,
      recurrenceWeekdays: recurrenceWeekdays ?? this.recurrenceWeekdays,
      createdAt: createdAt ?? this.createdAt,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (title.present) {
      map['title'] = Variable<String>(title.value);
    }
    if (description.present) {
      map['description'] = Variable<String>(description.value);
    }
    if (startAt.present) {
      map['start_at'] = Variable<int>(startAt.value);
    }
    if (endAt.present) {
      map['end_at'] = Variable<int>(endAt.value);
    }
    if (scheduledDate.present) {
      map['scheduled_date'] = Variable<int>(scheduledDate.value);
    }
    if (startTimeMinutes.present) {
      map['start_time_minutes'] = Variable<int>(startTimeMinutes.value);
    }
    if (durationMinutes.present) {
      map['duration_minutes'] = Variable<int>(durationMinutes.value);
    }
    if (categoryId.present) {
      map['category_id'] = Variable<String>(categoryId.value);
    }
    if (allDay.present) {
      map['all_day'] = Variable<int>(allDay.value);
    }
    if (priority.present) {
      map['priority'] = Variable<int>(priority.value);
    }
    if (isCompleted.present) {
      map['is_completed'] = Variable<int>(isCompleted.value);
    }
    if (recurrenceType.present) {
      map['recurrence_type'] = Variable<String>(recurrenceType.value);
    }
    if (recurrenceWeekdays.present) {
      map['recurrence_weekdays'] = Variable<int>(recurrenceWeekdays.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('TaskItemsCompanion(')
          ..write('id: $id, ')
          ..write('title: $title, ')
          ..write('description: $description, ')
          ..write('startAt: $startAt, ')
          ..write('endAt: $endAt, ')
          ..write('scheduledDate: $scheduledDate, ')
          ..write('startTimeMinutes: $startTimeMinutes, ')
          ..write('durationMinutes: $durationMinutes, ')
          ..write('categoryId: $categoryId, ')
          ..write('allDay: $allDay, ')
          ..write('priority: $priority, ')
          ..write('isCompleted: $isCompleted, ')
          ..write('recurrenceType: $recurrenceType, ')
          ..write('recurrenceWeekdays: $recurrenceWeekdays, ')
          ..write('createdAt: $createdAt, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class TaskOccurrenceStates extends Table
    with TableInfo<TaskOccurrenceStates, TaskOccurrenceStatesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  TaskOccurrenceStates(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> taskId = GeneratedColumn<String>(
    'task_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES task_items(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<int> occurrenceDate = GeneratedColumn<int>(
    'occurrence_date',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> isCompleted = GeneratedColumn<int>(
    'is_completed',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_completed IN (0, 1))',
    defaultValue: const CustomExpression('0'),
  );
  @override
  List<GeneratedColumn> get $columns => [taskId, occurrenceDate, isCompleted];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'task_occurrence_states';
  @override
  Set<GeneratedColumn> get $primaryKey => {taskId, occurrenceDate};
  @override
  TaskOccurrenceStatesData map(
    Map<String, dynamic> data, {
    String? tablePrefix,
  }) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return TaskOccurrenceStatesData(
      taskId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}task_id'],
      )!,
      occurrenceDate: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}occurrence_date'],
      )!,
      isCompleted: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}is_completed'],
      )!,
    );
  }

  @override
  TaskOccurrenceStates createAlias(String alias) {
    return TaskOccurrenceStates(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(task_id, occurrence_date)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class TaskOccurrenceStatesData extends DataClass
    implements Insertable<TaskOccurrenceStatesData> {
  final String taskId;
  final int occurrenceDate;
  final int isCompleted;
  const TaskOccurrenceStatesData({
    required this.taskId,
    required this.occurrenceDate,
    required this.isCompleted,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['task_id'] = Variable<String>(taskId);
    map['occurrence_date'] = Variable<int>(occurrenceDate);
    map['is_completed'] = Variable<int>(isCompleted);
    return map;
  }

  TaskOccurrenceStatesCompanion toCompanion(bool nullToAbsent) {
    return TaskOccurrenceStatesCompanion(
      taskId: Value(taskId),
      occurrenceDate: Value(occurrenceDate),
      isCompleted: Value(isCompleted),
    );
  }

  factory TaskOccurrenceStatesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return TaskOccurrenceStatesData(
      taskId: serializer.fromJson<String>(json['taskId']),
      occurrenceDate: serializer.fromJson<int>(json['occurrenceDate']),
      isCompleted: serializer.fromJson<int>(json['isCompleted']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'taskId': serializer.toJson<String>(taskId),
      'occurrenceDate': serializer.toJson<int>(occurrenceDate),
      'isCompleted': serializer.toJson<int>(isCompleted),
    };
  }

  TaskOccurrenceStatesData copyWith({
    String? taskId,
    int? occurrenceDate,
    int? isCompleted,
  }) => TaskOccurrenceStatesData(
    taskId: taskId ?? this.taskId,
    occurrenceDate: occurrenceDate ?? this.occurrenceDate,
    isCompleted: isCompleted ?? this.isCompleted,
  );
  TaskOccurrenceStatesData copyWithCompanion(
    TaskOccurrenceStatesCompanion data,
  ) {
    return TaskOccurrenceStatesData(
      taskId: data.taskId.present ? data.taskId.value : this.taskId,
      occurrenceDate: data.occurrenceDate.present
          ? data.occurrenceDate.value
          : this.occurrenceDate,
      isCompleted: data.isCompleted.present
          ? data.isCompleted.value
          : this.isCompleted,
    );
  }

  @override
  String toString() {
    return (StringBuffer('TaskOccurrenceStatesData(')
          ..write('taskId: $taskId, ')
          ..write('occurrenceDate: $occurrenceDate, ')
          ..write('isCompleted: $isCompleted')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(taskId, occurrenceDate, isCompleted);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TaskOccurrenceStatesData &&
          other.taskId == this.taskId &&
          other.occurrenceDate == this.occurrenceDate &&
          other.isCompleted == this.isCompleted);
}

class TaskOccurrenceStatesCompanion
    extends UpdateCompanion<TaskOccurrenceStatesData> {
  final Value<String> taskId;
  final Value<int> occurrenceDate;
  final Value<int> isCompleted;
  final Value<int> rowid;
  const TaskOccurrenceStatesCompanion({
    this.taskId = const Value.absent(),
    this.occurrenceDate = const Value.absent(),
    this.isCompleted = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  TaskOccurrenceStatesCompanion.insert({
    required String taskId,
    required int occurrenceDate,
    this.isCompleted = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : taskId = Value(taskId),
       occurrenceDate = Value(occurrenceDate);
  static Insertable<TaskOccurrenceStatesData> custom({
    Expression<String>? taskId,
    Expression<int>? occurrenceDate,
    Expression<int>? isCompleted,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (taskId != null) 'task_id': taskId,
      if (occurrenceDate != null) 'occurrence_date': occurrenceDate,
      if (isCompleted != null) 'is_completed': isCompleted,
      if (rowid != null) 'rowid': rowid,
    });
  }

  TaskOccurrenceStatesCompanion copyWith({
    Value<String>? taskId,
    Value<int>? occurrenceDate,
    Value<int>? isCompleted,
    Value<int>? rowid,
  }) {
    return TaskOccurrenceStatesCompanion(
      taskId: taskId ?? this.taskId,
      occurrenceDate: occurrenceDate ?? this.occurrenceDate,
      isCompleted: isCompleted ?? this.isCompleted,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (taskId.present) {
      map['task_id'] = Variable<String>(taskId.value);
    }
    if (occurrenceDate.present) {
      map['occurrence_date'] = Variable<int>(occurrenceDate.value);
    }
    if (isCompleted.present) {
      map['is_completed'] = Variable<int>(isCompleted.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('TaskOccurrenceStatesCompanion(')
          ..write('taskId: $taskId, ')
          ..write('occurrenceDate: $occurrenceDate, ')
          ..write('isCompleted: $isCompleted, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class TaskSubtasks extends Table
    with TableInfo<TaskSubtasks, TaskSubtasksData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  TaskSubtasks(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> taskId = GeneratedColumn<String>(
    'task_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES task_items(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<String> title = GeneratedColumn<String>(
    'title',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> sortOrder = GeneratedColumn<int>(
    'sort_order',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> isCompleted = GeneratedColumn<int>(
    'is_completed',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_completed IN (0, 1))',
    defaultValue: const CustomExpression('0'),
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    taskId,
    title,
    sortOrder,
    isCompleted,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'task_subtasks';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  TaskSubtasksData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return TaskSubtasksData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      taskId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}task_id'],
      )!,
      title: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}title'],
      )!,
      sortOrder: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}sort_order'],
      )!,
      isCompleted: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}is_completed'],
      )!,
    );
  }

  @override
  TaskSubtasks createAlias(String alias) {
    return TaskSubtasks(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class TaskSubtasksData extends DataClass
    implements Insertable<TaskSubtasksData> {
  final String id;
  final String taskId;
  final String title;
  final int sortOrder;
  final int isCompleted;
  const TaskSubtasksData({
    required this.id,
    required this.taskId,
    required this.title,
    required this.sortOrder,
    required this.isCompleted,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['task_id'] = Variable<String>(taskId);
    map['title'] = Variable<String>(title);
    map['sort_order'] = Variable<int>(sortOrder);
    map['is_completed'] = Variable<int>(isCompleted);
    return map;
  }

  TaskSubtasksCompanion toCompanion(bool nullToAbsent) {
    return TaskSubtasksCompanion(
      id: Value(id),
      taskId: Value(taskId),
      title: Value(title),
      sortOrder: Value(sortOrder),
      isCompleted: Value(isCompleted),
    );
  }

  factory TaskSubtasksData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return TaskSubtasksData(
      id: serializer.fromJson<String>(json['id']),
      taskId: serializer.fromJson<String>(json['taskId']),
      title: serializer.fromJson<String>(json['title']),
      sortOrder: serializer.fromJson<int>(json['sortOrder']),
      isCompleted: serializer.fromJson<int>(json['isCompleted']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'taskId': serializer.toJson<String>(taskId),
      'title': serializer.toJson<String>(title),
      'sortOrder': serializer.toJson<int>(sortOrder),
      'isCompleted': serializer.toJson<int>(isCompleted),
    };
  }

  TaskSubtasksData copyWith({
    String? id,
    String? taskId,
    String? title,
    int? sortOrder,
    int? isCompleted,
  }) => TaskSubtasksData(
    id: id ?? this.id,
    taskId: taskId ?? this.taskId,
    title: title ?? this.title,
    sortOrder: sortOrder ?? this.sortOrder,
    isCompleted: isCompleted ?? this.isCompleted,
  );
  TaskSubtasksData copyWithCompanion(TaskSubtasksCompanion data) {
    return TaskSubtasksData(
      id: data.id.present ? data.id.value : this.id,
      taskId: data.taskId.present ? data.taskId.value : this.taskId,
      title: data.title.present ? data.title.value : this.title,
      sortOrder: data.sortOrder.present ? data.sortOrder.value : this.sortOrder,
      isCompleted: data.isCompleted.present
          ? data.isCompleted.value
          : this.isCompleted,
    );
  }

  @override
  String toString() {
    return (StringBuffer('TaskSubtasksData(')
          ..write('id: $id, ')
          ..write('taskId: $taskId, ')
          ..write('title: $title, ')
          ..write('sortOrder: $sortOrder, ')
          ..write('isCompleted: $isCompleted')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, taskId, title, sortOrder, isCompleted);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TaskSubtasksData &&
          other.id == this.id &&
          other.taskId == this.taskId &&
          other.title == this.title &&
          other.sortOrder == this.sortOrder &&
          other.isCompleted == this.isCompleted);
}

class TaskSubtasksCompanion extends UpdateCompanion<TaskSubtasksData> {
  final Value<String> id;
  final Value<String> taskId;
  final Value<String> title;
  final Value<int> sortOrder;
  final Value<int> isCompleted;
  final Value<int> rowid;
  const TaskSubtasksCompanion({
    this.id = const Value.absent(),
    this.taskId = const Value.absent(),
    this.title = const Value.absent(),
    this.sortOrder = const Value.absent(),
    this.isCompleted = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  TaskSubtasksCompanion.insert({
    required String id,
    required String taskId,
    required String title,
    this.sortOrder = const Value.absent(),
    this.isCompleted = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       taskId = Value(taskId),
       title = Value(title);
  static Insertable<TaskSubtasksData> custom({
    Expression<String>? id,
    Expression<String>? taskId,
    Expression<String>? title,
    Expression<int>? sortOrder,
    Expression<int>? isCompleted,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (taskId != null) 'task_id': taskId,
      if (title != null) 'title': title,
      if (sortOrder != null) 'sort_order': sortOrder,
      if (isCompleted != null) 'is_completed': isCompleted,
      if (rowid != null) 'rowid': rowid,
    });
  }

  TaskSubtasksCompanion copyWith({
    Value<String>? id,
    Value<String>? taskId,
    Value<String>? title,
    Value<int>? sortOrder,
    Value<int>? isCompleted,
    Value<int>? rowid,
  }) {
    return TaskSubtasksCompanion(
      id: id ?? this.id,
      taskId: taskId ?? this.taskId,
      title: title ?? this.title,
      sortOrder: sortOrder ?? this.sortOrder,
      isCompleted: isCompleted ?? this.isCompleted,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (taskId.present) {
      map['task_id'] = Variable<String>(taskId.value);
    }
    if (title.present) {
      map['title'] = Variable<String>(title.value);
    }
    if (sortOrder.present) {
      map['sort_order'] = Variable<int>(sortOrder.value);
    }
    if (isCompleted.present) {
      map['is_completed'] = Variable<int>(isCompleted.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('TaskSubtasksCompanion(')
          ..write('id: $id, ')
          ..write('taskId: $taskId, ')
          ..write('title: $title, ')
          ..write('sortOrder: $sortOrder, ')
          ..write('isCompleted: $isCompleted, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class TaskSubtaskOccurrenceStates extends Table
    with
        TableInfo<
          TaskSubtaskOccurrenceStates,
          TaskSubtaskOccurrenceStatesData
        > {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  TaskSubtaskOccurrenceStates(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> subtaskId = GeneratedColumn<String>(
    'subtask_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES task_subtasks(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<int> occurrenceDate = GeneratedColumn<int>(
    'occurrence_date',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> isCompleted = GeneratedColumn<int>(
    'is_completed',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_completed IN (0, 1))',
    defaultValue: const CustomExpression('0'),
  );
  @override
  List<GeneratedColumn> get $columns => [
    subtaskId,
    occurrenceDate,
    isCompleted,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'task_subtask_occurrence_states';
  @override
  Set<GeneratedColumn> get $primaryKey => {subtaskId, occurrenceDate};
  @override
  TaskSubtaskOccurrenceStatesData map(
    Map<String, dynamic> data, {
    String? tablePrefix,
  }) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return TaskSubtaskOccurrenceStatesData(
      subtaskId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}subtask_id'],
      )!,
      occurrenceDate: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}occurrence_date'],
      )!,
      isCompleted: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}is_completed'],
      )!,
    );
  }

  @override
  TaskSubtaskOccurrenceStates createAlias(String alias) {
    return TaskSubtaskOccurrenceStates(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(subtask_id, occurrence_date)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class TaskSubtaskOccurrenceStatesData extends DataClass
    implements Insertable<TaskSubtaskOccurrenceStatesData> {
  final String subtaskId;
  final int occurrenceDate;
  final int isCompleted;
  const TaskSubtaskOccurrenceStatesData({
    required this.subtaskId,
    required this.occurrenceDate,
    required this.isCompleted,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['subtask_id'] = Variable<String>(subtaskId);
    map['occurrence_date'] = Variable<int>(occurrenceDate);
    map['is_completed'] = Variable<int>(isCompleted);
    return map;
  }

  TaskSubtaskOccurrenceStatesCompanion toCompanion(bool nullToAbsent) {
    return TaskSubtaskOccurrenceStatesCompanion(
      subtaskId: Value(subtaskId),
      occurrenceDate: Value(occurrenceDate),
      isCompleted: Value(isCompleted),
    );
  }

  factory TaskSubtaskOccurrenceStatesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return TaskSubtaskOccurrenceStatesData(
      subtaskId: serializer.fromJson<String>(json['subtaskId']),
      occurrenceDate: serializer.fromJson<int>(json['occurrenceDate']),
      isCompleted: serializer.fromJson<int>(json['isCompleted']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'subtaskId': serializer.toJson<String>(subtaskId),
      'occurrenceDate': serializer.toJson<int>(occurrenceDate),
      'isCompleted': serializer.toJson<int>(isCompleted),
    };
  }

  TaskSubtaskOccurrenceStatesData copyWith({
    String? subtaskId,
    int? occurrenceDate,
    int? isCompleted,
  }) => TaskSubtaskOccurrenceStatesData(
    subtaskId: subtaskId ?? this.subtaskId,
    occurrenceDate: occurrenceDate ?? this.occurrenceDate,
    isCompleted: isCompleted ?? this.isCompleted,
  );
  TaskSubtaskOccurrenceStatesData copyWithCompanion(
    TaskSubtaskOccurrenceStatesCompanion data,
  ) {
    return TaskSubtaskOccurrenceStatesData(
      subtaskId: data.subtaskId.present ? data.subtaskId.value : this.subtaskId,
      occurrenceDate: data.occurrenceDate.present
          ? data.occurrenceDate.value
          : this.occurrenceDate,
      isCompleted: data.isCompleted.present
          ? data.isCompleted.value
          : this.isCompleted,
    );
  }

  @override
  String toString() {
    return (StringBuffer('TaskSubtaskOccurrenceStatesData(')
          ..write('subtaskId: $subtaskId, ')
          ..write('occurrenceDate: $occurrenceDate, ')
          ..write('isCompleted: $isCompleted')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(subtaskId, occurrenceDate, isCompleted);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TaskSubtaskOccurrenceStatesData &&
          other.subtaskId == this.subtaskId &&
          other.occurrenceDate == this.occurrenceDate &&
          other.isCompleted == this.isCompleted);
}

class TaskSubtaskOccurrenceStatesCompanion
    extends UpdateCompanion<TaskSubtaskOccurrenceStatesData> {
  final Value<String> subtaskId;
  final Value<int> occurrenceDate;
  final Value<int> isCompleted;
  final Value<int> rowid;
  const TaskSubtaskOccurrenceStatesCompanion({
    this.subtaskId = const Value.absent(),
    this.occurrenceDate = const Value.absent(),
    this.isCompleted = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  TaskSubtaskOccurrenceStatesCompanion.insert({
    required String subtaskId,
    required int occurrenceDate,
    this.isCompleted = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : subtaskId = Value(subtaskId),
       occurrenceDate = Value(occurrenceDate);
  static Insertable<TaskSubtaskOccurrenceStatesData> custom({
    Expression<String>? subtaskId,
    Expression<int>? occurrenceDate,
    Expression<int>? isCompleted,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (subtaskId != null) 'subtask_id': subtaskId,
      if (occurrenceDate != null) 'occurrence_date': occurrenceDate,
      if (isCompleted != null) 'is_completed': isCompleted,
      if (rowid != null) 'rowid': rowid,
    });
  }

  TaskSubtaskOccurrenceStatesCompanion copyWith({
    Value<String>? subtaskId,
    Value<int>? occurrenceDate,
    Value<int>? isCompleted,
    Value<int>? rowid,
  }) {
    return TaskSubtaskOccurrenceStatesCompanion(
      subtaskId: subtaskId ?? this.subtaskId,
      occurrenceDate: occurrenceDate ?? this.occurrenceDate,
      isCompleted: isCompleted ?? this.isCompleted,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (subtaskId.present) {
      map['subtask_id'] = Variable<String>(subtaskId.value);
    }
    if (occurrenceDate.present) {
      map['occurrence_date'] = Variable<int>(occurrenceDate.value);
    }
    if (isCompleted.present) {
      map['is_completed'] = Variable<int>(isCompleted.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('TaskSubtaskOccurrenceStatesCompanion(')
          ..write('subtaskId: $subtaskId, ')
          ..write('occurrenceDate: $occurrenceDate, ')
          ..write('isCompleted: $isCompleted, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class TaskOccurrenceOverrides extends Table
    with TableInfo<TaskOccurrenceOverrides, TaskOccurrenceOverridesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  TaskOccurrenceOverrides(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> taskId = GeneratedColumn<String>(
    'task_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES task_items(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<int> occurrenceDate = GeneratedColumn<int>(
    'occurrence_date',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> effectiveDate = GeneratedColumn<int>(
    'effective_date',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> title = GeneratedColumn<String>(
    'title',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> description = GeneratedColumn<String>(
    'description',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<int> startTimeMinutes = GeneratedColumn<int>(
    'start_time_minutes',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> durationMinutes = GeneratedColumn<int>(
    'duration_minutes',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> categoryId = GeneratedColumn<String>(
    'category_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL REFERENCES task_categories(id)ON DELETE SET NULL',
  );
  late final GeneratedColumn<int> allDay = GeneratedColumn<int>(
    'all_day',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0 CHECK (all_day IN (0, 1))',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> priority = GeneratedColumn<int>(
    'priority',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1',
    defaultValue: const CustomExpression('1'),
  );
  late final GeneratedColumn<int> isDeleted = GeneratedColumn<int>(
    'is_deleted',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1))',
    defaultValue: const CustomExpression('0'),
  );
  @override
  List<GeneratedColumn> get $columns => [
    taskId,
    occurrenceDate,
    effectiveDate,
    title,
    description,
    startTimeMinutes,
    durationMinutes,
    categoryId,
    allDay,
    priority,
    isDeleted,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'task_occurrence_overrides';
  @override
  Set<GeneratedColumn> get $primaryKey => {taskId, occurrenceDate};
  @override
  TaskOccurrenceOverridesData map(
    Map<String, dynamic> data, {
    String? tablePrefix,
  }) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return TaskOccurrenceOverridesData(
      taskId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}task_id'],
      )!,
      occurrenceDate: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}occurrence_date'],
      )!,
      effectiveDate: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}effective_date'],
      )!,
      title: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}title'],
      )!,
      description: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}description'],
      )!,
      startTimeMinutes: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}start_time_minutes'],
      ),
      durationMinutes: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}duration_minutes'],
      ),
      categoryId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}category_id'],
      ),
      allDay: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}all_day'],
      )!,
      priority: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}priority'],
      )!,
      isDeleted: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}is_deleted'],
      )!,
    );
  }

  @override
  TaskOccurrenceOverrides createAlias(String alias) {
    return TaskOccurrenceOverrides(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(task_id, occurrence_date)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class TaskOccurrenceOverridesData extends DataClass
    implements Insertable<TaskOccurrenceOverridesData> {
  final String taskId;
  final int occurrenceDate;
  final int effectiveDate;
  final String title;
  final String description;
  final int? startTimeMinutes;
  final int? durationMinutes;
  final String? categoryId;
  final int allDay;
  final int priority;
  final int isDeleted;
  const TaskOccurrenceOverridesData({
    required this.taskId,
    required this.occurrenceDate,
    required this.effectiveDate,
    required this.title,
    required this.description,
    this.startTimeMinutes,
    this.durationMinutes,
    this.categoryId,
    required this.allDay,
    required this.priority,
    required this.isDeleted,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['task_id'] = Variable<String>(taskId);
    map['occurrence_date'] = Variable<int>(occurrenceDate);
    map['effective_date'] = Variable<int>(effectiveDate);
    map['title'] = Variable<String>(title);
    map['description'] = Variable<String>(description);
    if (!nullToAbsent || startTimeMinutes != null) {
      map['start_time_minutes'] = Variable<int>(startTimeMinutes);
    }
    if (!nullToAbsent || durationMinutes != null) {
      map['duration_minutes'] = Variable<int>(durationMinutes);
    }
    if (!nullToAbsent || categoryId != null) {
      map['category_id'] = Variable<String>(categoryId);
    }
    map['all_day'] = Variable<int>(allDay);
    map['priority'] = Variable<int>(priority);
    map['is_deleted'] = Variable<int>(isDeleted);
    return map;
  }

  TaskOccurrenceOverridesCompanion toCompanion(bool nullToAbsent) {
    return TaskOccurrenceOverridesCompanion(
      taskId: Value(taskId),
      occurrenceDate: Value(occurrenceDate),
      effectiveDate: Value(effectiveDate),
      title: Value(title),
      description: Value(description),
      startTimeMinutes: startTimeMinutes == null && nullToAbsent
          ? const Value.absent()
          : Value(startTimeMinutes),
      durationMinutes: durationMinutes == null && nullToAbsent
          ? const Value.absent()
          : Value(durationMinutes),
      categoryId: categoryId == null && nullToAbsent
          ? const Value.absent()
          : Value(categoryId),
      allDay: Value(allDay),
      priority: Value(priority),
      isDeleted: Value(isDeleted),
    );
  }

  factory TaskOccurrenceOverridesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return TaskOccurrenceOverridesData(
      taskId: serializer.fromJson<String>(json['taskId']),
      occurrenceDate: serializer.fromJson<int>(json['occurrenceDate']),
      effectiveDate: serializer.fromJson<int>(json['effectiveDate']),
      title: serializer.fromJson<String>(json['title']),
      description: serializer.fromJson<String>(json['description']),
      startTimeMinutes: serializer.fromJson<int?>(json['startTimeMinutes']),
      durationMinutes: serializer.fromJson<int?>(json['durationMinutes']),
      categoryId: serializer.fromJson<String?>(json['categoryId']),
      allDay: serializer.fromJson<int>(json['allDay']),
      priority: serializer.fromJson<int>(json['priority']),
      isDeleted: serializer.fromJson<int>(json['isDeleted']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'taskId': serializer.toJson<String>(taskId),
      'occurrenceDate': serializer.toJson<int>(occurrenceDate),
      'effectiveDate': serializer.toJson<int>(effectiveDate),
      'title': serializer.toJson<String>(title),
      'description': serializer.toJson<String>(description),
      'startTimeMinutes': serializer.toJson<int?>(startTimeMinutes),
      'durationMinutes': serializer.toJson<int?>(durationMinutes),
      'categoryId': serializer.toJson<String?>(categoryId),
      'allDay': serializer.toJson<int>(allDay),
      'priority': serializer.toJson<int>(priority),
      'isDeleted': serializer.toJson<int>(isDeleted),
    };
  }

  TaskOccurrenceOverridesData copyWith({
    String? taskId,
    int? occurrenceDate,
    int? effectiveDate,
    String? title,
    String? description,
    Value<int?> startTimeMinutes = const Value.absent(),
    Value<int?> durationMinutes = const Value.absent(),
    Value<String?> categoryId = const Value.absent(),
    int? allDay,
    int? priority,
    int? isDeleted,
  }) => TaskOccurrenceOverridesData(
    taskId: taskId ?? this.taskId,
    occurrenceDate: occurrenceDate ?? this.occurrenceDate,
    effectiveDate: effectiveDate ?? this.effectiveDate,
    title: title ?? this.title,
    description: description ?? this.description,
    startTimeMinutes: startTimeMinutes.present
        ? startTimeMinutes.value
        : this.startTimeMinutes,
    durationMinutes: durationMinutes.present
        ? durationMinutes.value
        : this.durationMinutes,
    categoryId: categoryId.present ? categoryId.value : this.categoryId,
    allDay: allDay ?? this.allDay,
    priority: priority ?? this.priority,
    isDeleted: isDeleted ?? this.isDeleted,
  );
  TaskOccurrenceOverridesData copyWithCompanion(
    TaskOccurrenceOverridesCompanion data,
  ) {
    return TaskOccurrenceOverridesData(
      taskId: data.taskId.present ? data.taskId.value : this.taskId,
      occurrenceDate: data.occurrenceDate.present
          ? data.occurrenceDate.value
          : this.occurrenceDate,
      effectiveDate: data.effectiveDate.present
          ? data.effectiveDate.value
          : this.effectiveDate,
      title: data.title.present ? data.title.value : this.title,
      description: data.description.present
          ? data.description.value
          : this.description,
      startTimeMinutes: data.startTimeMinutes.present
          ? data.startTimeMinutes.value
          : this.startTimeMinutes,
      durationMinutes: data.durationMinutes.present
          ? data.durationMinutes.value
          : this.durationMinutes,
      categoryId: data.categoryId.present
          ? data.categoryId.value
          : this.categoryId,
      allDay: data.allDay.present ? data.allDay.value : this.allDay,
      priority: data.priority.present ? data.priority.value : this.priority,
      isDeleted: data.isDeleted.present ? data.isDeleted.value : this.isDeleted,
    );
  }

  @override
  String toString() {
    return (StringBuffer('TaskOccurrenceOverridesData(')
          ..write('taskId: $taskId, ')
          ..write('occurrenceDate: $occurrenceDate, ')
          ..write('effectiveDate: $effectiveDate, ')
          ..write('title: $title, ')
          ..write('description: $description, ')
          ..write('startTimeMinutes: $startTimeMinutes, ')
          ..write('durationMinutes: $durationMinutes, ')
          ..write('categoryId: $categoryId, ')
          ..write('allDay: $allDay, ')
          ..write('priority: $priority, ')
          ..write('isDeleted: $isDeleted')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    taskId,
    occurrenceDate,
    effectiveDate,
    title,
    description,
    startTimeMinutes,
    durationMinutes,
    categoryId,
    allDay,
    priority,
    isDeleted,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TaskOccurrenceOverridesData &&
          other.taskId == this.taskId &&
          other.occurrenceDate == this.occurrenceDate &&
          other.effectiveDate == this.effectiveDate &&
          other.title == this.title &&
          other.description == this.description &&
          other.startTimeMinutes == this.startTimeMinutes &&
          other.durationMinutes == this.durationMinutes &&
          other.categoryId == this.categoryId &&
          other.allDay == this.allDay &&
          other.priority == this.priority &&
          other.isDeleted == this.isDeleted);
}

class TaskOccurrenceOverridesCompanion
    extends UpdateCompanion<TaskOccurrenceOverridesData> {
  final Value<String> taskId;
  final Value<int> occurrenceDate;
  final Value<int> effectiveDate;
  final Value<String> title;
  final Value<String> description;
  final Value<int?> startTimeMinutes;
  final Value<int?> durationMinutes;
  final Value<String?> categoryId;
  final Value<int> allDay;
  final Value<int> priority;
  final Value<int> isDeleted;
  final Value<int> rowid;
  const TaskOccurrenceOverridesCompanion({
    this.taskId = const Value.absent(),
    this.occurrenceDate = const Value.absent(),
    this.effectiveDate = const Value.absent(),
    this.title = const Value.absent(),
    this.description = const Value.absent(),
    this.startTimeMinutes = const Value.absent(),
    this.durationMinutes = const Value.absent(),
    this.categoryId = const Value.absent(),
    this.allDay = const Value.absent(),
    this.priority = const Value.absent(),
    this.isDeleted = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  TaskOccurrenceOverridesCompanion.insert({
    required String taskId,
    required int occurrenceDate,
    required int effectiveDate,
    required String title,
    this.description = const Value.absent(),
    this.startTimeMinutes = const Value.absent(),
    this.durationMinutes = const Value.absent(),
    this.categoryId = const Value.absent(),
    this.allDay = const Value.absent(),
    this.priority = const Value.absent(),
    this.isDeleted = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : taskId = Value(taskId),
       occurrenceDate = Value(occurrenceDate),
       effectiveDate = Value(effectiveDate),
       title = Value(title);
  static Insertable<TaskOccurrenceOverridesData> custom({
    Expression<String>? taskId,
    Expression<int>? occurrenceDate,
    Expression<int>? effectiveDate,
    Expression<String>? title,
    Expression<String>? description,
    Expression<int>? startTimeMinutes,
    Expression<int>? durationMinutes,
    Expression<String>? categoryId,
    Expression<int>? allDay,
    Expression<int>? priority,
    Expression<int>? isDeleted,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (taskId != null) 'task_id': taskId,
      if (occurrenceDate != null) 'occurrence_date': occurrenceDate,
      if (effectiveDate != null) 'effective_date': effectiveDate,
      if (title != null) 'title': title,
      if (description != null) 'description': description,
      if (startTimeMinutes != null) 'start_time_minutes': startTimeMinutes,
      if (durationMinutes != null) 'duration_minutes': durationMinutes,
      if (categoryId != null) 'category_id': categoryId,
      if (allDay != null) 'all_day': allDay,
      if (priority != null) 'priority': priority,
      if (isDeleted != null) 'is_deleted': isDeleted,
      if (rowid != null) 'rowid': rowid,
    });
  }

  TaskOccurrenceOverridesCompanion copyWith({
    Value<String>? taskId,
    Value<int>? occurrenceDate,
    Value<int>? effectiveDate,
    Value<String>? title,
    Value<String>? description,
    Value<int?>? startTimeMinutes,
    Value<int?>? durationMinutes,
    Value<String?>? categoryId,
    Value<int>? allDay,
    Value<int>? priority,
    Value<int>? isDeleted,
    Value<int>? rowid,
  }) {
    return TaskOccurrenceOverridesCompanion(
      taskId: taskId ?? this.taskId,
      occurrenceDate: occurrenceDate ?? this.occurrenceDate,
      effectiveDate: effectiveDate ?? this.effectiveDate,
      title: title ?? this.title,
      description: description ?? this.description,
      startTimeMinutes: startTimeMinutes ?? this.startTimeMinutes,
      durationMinutes: durationMinutes ?? this.durationMinutes,
      categoryId: categoryId ?? this.categoryId,
      allDay: allDay ?? this.allDay,
      priority: priority ?? this.priority,
      isDeleted: isDeleted ?? this.isDeleted,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (taskId.present) {
      map['task_id'] = Variable<String>(taskId.value);
    }
    if (occurrenceDate.present) {
      map['occurrence_date'] = Variable<int>(occurrenceDate.value);
    }
    if (effectiveDate.present) {
      map['effective_date'] = Variable<int>(effectiveDate.value);
    }
    if (title.present) {
      map['title'] = Variable<String>(title.value);
    }
    if (description.present) {
      map['description'] = Variable<String>(description.value);
    }
    if (startTimeMinutes.present) {
      map['start_time_minutes'] = Variable<int>(startTimeMinutes.value);
    }
    if (durationMinutes.present) {
      map['duration_minutes'] = Variable<int>(durationMinutes.value);
    }
    if (categoryId.present) {
      map['category_id'] = Variable<String>(categoryId.value);
    }
    if (allDay.present) {
      map['all_day'] = Variable<int>(allDay.value);
    }
    if (priority.present) {
      map['priority'] = Variable<int>(priority.value);
    }
    if (isDeleted.present) {
      map['is_deleted'] = Variable<int>(isDeleted.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('TaskOccurrenceOverridesCompanion(')
          ..write('taskId: $taskId, ')
          ..write('occurrenceDate: $occurrenceDate, ')
          ..write('effectiveDate: $effectiveDate, ')
          ..write('title: $title, ')
          ..write('description: $description, ')
          ..write('startTimeMinutes: $startTimeMinutes, ')
          ..write('durationMinutes: $durationMinutes, ')
          ..write('categoryId: $categoryId, ')
          ..write('allDay: $allDay, ')
          ..write('priority: $priority, ')
          ..write('isDeleted: $isDeleted, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV6 extends GeneratedDatabase {
  DatabaseAtV6(QueryExecutor e) : super(e);
  late final TaskCategories taskCategories = TaskCategories(this);
  late final TaskItems taskItems = TaskItems(this);
  late final TaskOccurrenceStates taskOccurrenceStates = TaskOccurrenceStates(
    this,
  );
  late final TaskSubtasks taskSubtasks = TaskSubtasks(this);
  late final TaskSubtaskOccurrenceStates taskSubtaskOccurrenceStates =
      TaskSubtaskOccurrenceStates(this);
  late final TaskOccurrenceOverrides taskOccurrenceOverrides =
      TaskOccurrenceOverrides(this);
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    taskCategories,
    taskItems,
    taskOccurrenceStates,
    taskSubtasks,
    taskSubtaskOccurrenceStates,
    taskOccurrenceOverrides,
  ];
  @override
  StreamQueryUpdateRules get streamUpdateRules => const StreamQueryUpdateRules([
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'task_categories',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('task_items', kind: UpdateKind.update)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'task_items',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('task_occurrence_states', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'task_items',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('task_subtasks', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'task_subtasks',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [
        TableUpdate('task_subtask_occurrence_states', kind: UpdateKind.delete),
      ],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'task_items',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [
        TableUpdate('task_occurrence_overrides', kind: UpdateKind.delete),
      ],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'task_categories',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [
        TableUpdate('task_occurrence_overrides', kind: UpdateKind.update),
      ],
    ),
  ]);
  @override
  int get schemaVersion => 6;
}
